### PR TITLE
Feature/fixes

### PR DESCRIPTION
**Pull request by trasher**

### CODE REVIEW

**Comment by cconard96** [comment]
What is the difference with the tables in the CLI docs?

**Comment by trasher** [comment]
Existing ones were incorrect:
```
/home/trasher/Workdir/docs/user/source/cli.rst:877: WARNING: Malformed table.
Text in column margin in table line 6.

=================  ========  ================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================  ========  =======  =====  =========
Name               Shortcut  Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Required  Default  Array  Negatable
-----------------  --------  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  --------  -------  -----  ---------
--dictionnary      -d        Dictionnary to use. Possible values are: CableType, ComputerModel, ComputerType, DatabaseInstanceType, Glpi\SocketModel, ImageFormat, ImageResolution, Manufacturer, MonitorModel, MonitorType, NetworkEquipmentModel, NetworkEquipmentType, OperatingSystem, OperatingSystemArchitecture, OperatingSystemEdition, OperatingSystemKernel, OperatingSystemKernelVersion, OperatingSystemServicePack, OperatingSystemVersion, PeripheralModel, PeripheralType, PhoneModel, PhoneType, Printer, PrinterModel, PrinterType, Software  Yes                No     No
--manufacturer-id  -m        If option is set, only items having given manufacturer ID will be processed.
Currently only available for Software dictionnary.                                                                                                                                                                                                                                                                                                                                                                                                   Yes                No     No
=================  ========  ================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================  ========  =======  =====  =========
```

**Comment by cconard96** [comment]
Looks like newlines aren't handled properly. I only asked because the docs were generated automatically and only a few needed replaced.

Should the tool I made for this be updated to use list-tables for everything (and fix newlines)?

**Comment by trasher** [comment]
> Looks like newlines aren't handled properly.

You mean with the "simple" syntax? Or with the changes I made?

> I only asked because the docs were generated automatically and only a few needed replaced.
> 
> Should the tool I made for this be updated to use list-tables for everything (and fix newlines)?

I do forget you generate this one from a script... So yes, it should be changed to use the `list-table` syntax that seems to provide/support more features. Also, the way it looks like is different, therefore using `list-table` everywhere should be a good solution.

**Comment by cconard96** [comment]
> > Looks like newlines aren't handled properly.
> 
> You mean with the "simple" syntax? Or with the changes I made?
> 

The simple syntax, but also that my script didn't remove line breaks.

I'll update the script to use the other format and maybe add a comment somewhere stating the page is automatically generated.

**Comment by trasher** [comment]
Should we merge this one anyway?

**Comment by cconard96** [comment]
That is OK with me.

**Review by cconard96 — APPROVED** [review]

**Pull request merged**
