### PR TITLE
Add :alt: tags to make images more accessible

### PR DESCRIPTION
**Pull request by bzg**

### CODE REVIEW

**Comment by bzg** [comment]
Ok, here is the updated PR. I have replaced `.md` files by `.rst` files and tried to fix a few references - there is lot left to be done here, I cannot commit more time to this right now.

The documentation is crucial to some users, I hope this will get merged and updated further.

Thanks!

**Comment by bzg** [comment]
Hi, is there anything I should do to get this PR merged? Thanks!

**Comment by trasher** [comment]
Hello,

Sorry, I forget to merge :)

**Comment by bzg** [comment]
Thanks!

**Pull request merged**
